### ISSUE TITLE
CPU 100%

### ISSUE THREAD

**Issue by meishileguangguang** [chenqihui/QHScreenCAPDemo#1]
请问录屏的时候CPU 一直100%，怎么处理？谢谢

**Comment by chenqihui** [comment]
嗯嗯，你试试在 ASScreenRecorder.m 文件的函数 startRecording
设置下 _displayLink 的刷新次数。
```
        if ([UIDevice currentDevice].systemVersion.floatValue >= 10.0) {
            _displayLink.preferredFramesPerSecond = 20;
        }
        else {
            _displayLink.frameInterval = 3;
        }
```

**Comment by meishileguangguang** [comment]
非常感谢，试了一下，设置1秒15帧的话 CPU 占用率88%左右，请问还有什么参数可以设置的吗？

**Comment by chenqihui** [comment]
我刚试了Demo为20，CPU是到60-70，没你那边这么高喔。其他参数么，大部分是设置写出流的，应该不管事。这里消耗就是截屏的API。不过这API也是这个功能的核心，有好修改，欢迎 merge request 哈。
